# config.yaml
database:
  username: retail_db_user
  password: retail_db_password
  host: localhost
  port: 5432
  dbname: retail_store_db

pyspark:
  input_file: export (1).csv

xgboost:
  n_estimators: 45
  learning_rate: 0.05
  max_depth: 6
  subsample: 0.8
  colsample_bytree: 0.8